apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testGithub
  annotations:
    github.com/project-slug: KalyaniNakatNineleaps/testGithub
spec:
  type: other
  lifecycle: unknown
  owner: team-b
